# Generated by Django 5.1.7 on 2025-06-04 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserSemester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("2025.1", "2025.1"),
                            ("2025.2", "2025.2"),
                            ("2026.1", "2026.1"),
                        ],
                        max_length=10,
                    ),
                ),
                ("course", models.CharField(max_length=100)),
                (
                    "subjects",
                    models.ManyToManyField(blank=True, to="calendarapp.subject"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_semester",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
