# Generated by Django 5.1.7 on 2025-05-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_project_options_alter_task_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
