# Generated by Django 5.1.7 on 2025-05-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_delete_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Conclusão"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Início"
            ),
        ),
    ]
